#!/usr/bin/env python
# -*- coding: utf-8 -*-
import time

from django.http import JsonResponse
from django.shortcuts import render
# Create your views here.


def index(request):
    return render(request, 'monitoring/base.html')


def search_form(request):
    return render(request, 'search_form.html')


def search_results(request):
    return render(request, 'search_results.html')


def decision_edit(request):
    return render(request, 'decision_edit.html')


def json(request):
    time.sleep(10)
    result = [{
        'id': 0,
        'decision_form': 'Рішення',
        'adoption_date': '01.01.2012',
        'force_entry_date': '10.01.2012',
        'judicial_form': 'Цивільне',
        'case_number': '1',
        'court_name': 'Рівненський апеляційний суд',
        'text': 'Lorem ipsum Nisi voluptate ut culpa exercitation.',
        'competence': '',
        'claimants': [''],
        'defendants': [''],
        'third_parties': [''],
        'claim_subject': '',
        'material': '',
        'case_price': '',
        'ground': '',
        'ground_square': '',
        'legality': '',
        'appealable': '',
        'complete': ''
    },

        {
            'id': 1,
            'decision_form': 'Постанова',
            'adoption_date': '02.02.2013',
            'force_entry_date': '12.02.2013',
            'judicial_form': 'Адміністративне',
            'case_number': '2',
            'court_name': 'Рівненський окружний адміністративний суд',
            'text': 'Lorem ipsum Nisi voluptate ut culpa exercitation.',
            'competence': '',
            'claimants': [''],
            'defendants': [''],
            'third_parties': [''],
            'claim_subject': '',
            'material': '',
            'case_price': '',
            'ground': '',
            'ground_square': '',
            'legality': '',
            'appealable': '',
            'complete': ''
    },

        {
            'id': 2,
            'decision_form': 'Ухвала',
            'adoption_date': '03.03.2014',
            'force_entry_date': '13.03.2014',
            'judicial_form': 'Господарське',
            'case_number': '3',
            'court_name': 'Рівненський апеляційний господарський суд',
            'text': 'Lorem ipsum Nisi voluptate ut culpa exercitation.',
            'competence': '',
            'claimants': [''],
            'defendants': [''],
            'third_parties': [''],
            'claim_subject': '',
            'material': '',
            'case_price': '',
            'ground': '',
            'ground_square': '',
            'legality': '',
            'appealable': '',
            'complete': ''
    },

        {
            'id': 3,
            'decision_form': 'Ухвала',
            'adoption_date': '03.03.2014',
            'force_entry_date': '13.03.2014',
            'judicial_form': 'Господарське',
            'case_number': '3',
            'court_name': 'Рівненський апеляційний господарський суд',
            'text': 'Lorem ipsum Nisi voluptate ut culpa exercitation.',
            'competence': '',
            'claimants': [''],
            'defendants': [''],
            'third_parties': [''],
            'claim_subject': '',
            'material': '',
            'case_price': '',
            'ground': '',
            'ground_square': '',
            'legality': '',
            'appealable': '',
            'complete': ''
    },

        {
            'id': 4,
            'decision_form': 'Ухвала',
            'adoption_date': '03.03.2014',
            'force_entry_date': '13.03.2014',
            'judicial_form': 'Господарське',
            'case_number': '3',
            'court_name': 'Рівненський апеляційний господарський суд',
            'text': 'Lorem ipsum Nisi voluptate ut culpa exercitation.',
            'competence': '',
            'claimants': [''],
            'defendants': [''],
            'third_parties': [''],
            'claim_subject': '',
            'material': '',
            'case_price': '',
            'ground': '',
            'ground_square': '',
            'legality': '',
            'appealable': '',
            'complete': ''
    },

        {
            'id': 5,
            'decision_form': 'Ухвала',
            'adoption_date': '03.03.2014',
            'force_entry_date': '13.03.2014',
            'judicial_form': 'Господарське',
            'case_number': '3',
            'court_name': 'Рівненський апеляційний господарський суд',
            'text': 'Lorem ipsum Nisi voluptate ut culpa exercitation.',
            'competence': '',
            'claimants': [''],
            'defendants': [''],
            'third_parties': [''],
            'claim_subject': '',
            'material': '',
            'case_price': '',
            'ground': '',
            'ground_square': '',
            'legality': '',
            'appealable': '',
            'complete': ''
    },

        {
            'id': 6,
            'decision_form': 'Ухвала',
            'adoption_date': '03.03.2014',
            'force_entry_date': '13.03.2014',
            'judicial_form': 'Господарське',
            'case_number': '3',
            'court_name': 'Рівненський апеляційний господарський суд',
            'text': 'Lorem ipsum Nisi voluptate ut culpa exercitation.',
            'competence': '',
            'claimants': [''],
            'defendants': [''],
            'third_parties': [''],
            'claim_subject': '',
            'material': '',
            'case_price': '',
            'ground': '',
            'ground_square': '',
            'legality': '',
            'appealable': '',
            'complete': ''
    },

        {
            'id': 7,
            'decision_form': 'Ухвала',
            'adoption_date': '03.03.2014',
            'force_entry_date': '13.03.2014',
            'judicial_form': 'Господарське',
            'case_number': '3',
            'court_name': 'Рівненський апеляційний господарський суд',
            'text': 'Lorem ipsum Nisi voluptate ut culpa exercitation.',
            'competence': '',
            'claimants': [''],
            'defendants': [''],
            'third_parties': [''],
            'claim_subject': '',
            'material': '',
            'case_price': '',
            'ground': '',
            'ground_square': '',
            'legality': '',
            'appealable': '',
            'complete': ''
    },

        {
            'id': 8,
            'decision_form': 'Постанова',
            'adoption_date': '02.02.2013',
            'force_entry_date': '12.02.2013',
            'judicial_form': 'Адміністративне',
            'case_number': '2',
            'court_name': 'Рівненський окружний адміністративний суд',
            'text': 'Lorem ipsum Nisi voluptate ut culpa exercitation.',
            'competence': '',
            'claimants': [''],
            'defendants': [''],
            'third_parties': [''],
            'claim_subject': '',
            'material': '',
            'case_price': '',
            'ground': '',
            'ground_square': '',
            'legality': '',
            'appealable': '',
            'complete': ''
    },

        {
            'id': 9,
            'decision_form': 'Ухвала',
            'adoption_date': '03.03.2014',
            'force_entry_date': '13.03.2014',
            'judicial_form': 'Господарське',
            'case_number': '3',
            'court_name': 'Рівненський апеляційний господарський суд',
            'text': 'Lorem ipsum Nisi voluptate ut culpa exercitation.',
            'competence': '',
            'claimants': [''],
            'defendants': [''],
            'third_parties': [''],
            'claim_subject': '',
            'material': '',
            'case_price': '',
            'ground': '',
            'ground_square': '',
            'legality': '',
            'appealable': '',
            'complete': ''
    },
        {
            'id': 10,
            'decision_form': 'Постанова',
            'adoption_date': '02.02.2013',
            'force_entry_date': '12.02.2013',
            'judicial_form': 'Адміністративне',
            'case_number': '2',
            'court_name': 'Рівненський окружний адміністративний суд',
            'text': 'Lorem ipsum Nisi voluptate ut culpa exercitation.',
            'competence': '',
            'claimants': [''],
            'defendants': [''],
            'third_parties': [''],
            'claim_subject': '',
            'material': '',
            'case_price': '',
            'ground': '',
            'ground_square': '',
            'legality': '',
            'appealable': '',
            'complete': ''
    },

        {
            'id': 11,
            'decision_form': 'Ухвала',
            'adoption_date': '03.03.2014',
            'force_entry_date': '13.03.2014',
            'judicial_form': 'Господарське',
            'case_number': '3',
            'court_name': 'Рівненський апеляційний господарський суд',
            'text': 'Lorem ipsum Nisi voluptate ut culpa exercitation.',
            'competence': '',
            'claimants': [''],
            'defendants': [''],
            'third_parties': [''],
            'claim_subject': '',
            'material': '',
            'case_price': '',
            'ground': '',
            'ground_square': '',
            'legality': '',
            'appealable': '',
            'complete': ''
    },
        {
            'id': 12,
            'decision_form': 'Постанова',
            'adoption_date': '02.02.2013',
            'force_entry_date': '12.02.2013',
            'judicial_form': 'Адміністративне',
            'case_number': '2',
            'court_name': 'Рівненський окружний адміністративний суд',
            'text': 'Lorem ipsum Nisi voluptate ut culpa exercitation.',
            'competence': '',
            'claimants': [''],
            'defendants': [''],
            'third_parties': [''],
            'claim_subject': '',
            'material': '',
            'case_price': '',
            'ground': '',
            'ground_square': '',
            'legality': '',
            'appealable': '',
            'complete': ''
    },

        {
            'id': 13,
            'decision_form': 'Ухвала',
            'adoption_date': '03.03.2014',
            'force_entry_date': '13.03.2014',
            'judicial_form': 'Господарське',
            'case_number': '3',
            'court_name': 'Рівненський апеляційний господарський суд',
            'text': 'Lorem ipsum Nisi voluptate ut culpa exercitation.',
            'competence': '',
            'claimants': [''],
            'defendants': [''],
            'third_parties': [''],
            'claim_subject': '',
            'material': '',
            'case_price': '',
            'ground': '',
            'ground_square': '',
            'legality': '',
            'appealable': '',
            'complete': ''
    },
        {
            'id': 14,
            'decision_form': 'Постанова',
            'adoption_date': '02.02.2013',
            'force_entry_date': '12.02.2013',
            'judicial_form': 'Адміністративне',
            'case_number': '2',
            'court_name': 'Рівненський окружний адміністративний суд',
            'text': 'Lorem ipsum Nisi voluptate ut culpa exercitation.',
            'competence': '',
            'claimants': [''],
            'defendants': [''],
            'third_parties': [''],
            'claim_subject': '',
            'material': '',
            'case_price': '',
            'ground': '',
            'ground_square': '',
            'legality': '',
            'appealable': '',
            'complete': ''
    },

        {
            'id': 15,
            'decision_form': 'Ухвала',
            'adoption_date': '03.03.2014',
            'force_entry_date': '13.03.2014',
            'judicial_form': 'Господарське',
            'case_number': '3',
            'court_name': 'Рівненський апеляційний господарський суд',
            'text': 'Lorem ipsum Nisi voluptate ut culpa exercitation.',
            'competence': '',
            'claimants': [''],
            'defendants': [''],
            'third_parties': [''],
            'claim_subject': '',
            'material': '',
            'case_price': '',
            'ground': '',
            'ground_square': '',
            'legality': '',
            'appealable': '',
            'complete': ''
    },
        {
            'id': 16,
            'decision_form': 'Постанова',
            'adoption_date': '02.02.2013',
            'force_entry_date': '12.02.2013',
            'judicial_form': 'Адміністративне',
            'case_number': '2',
            'court_name': 'Рівненський окружний адміністративний суд',
            'text': 'Lorem ipsum Nisi voluptate ut culpa exercitation.',
            'competence': '',
            'claimants': [''],
            'defendants': [''],
            'third_parties': [''],
            'claim_subject': '',
            'material': '',
            'case_price': '',
            'ground': '',
            'ground_square': '',
            'legality': '',
            'appealable': '',
            'complete': ''
    },

        {
            'id': 17,
            'decision_form': 'Ухвала',
            'adoption_date': '03.03.2014',
            'force_entry_date': '13.03.2014',
            'judicial_form': 'Господарське',
            'case_number': '3',
            'court_name': 'Рівненський апеляційний господарський суд',
            'text': 'Lorem ipsum Nisi voluptate ut culpa exercitation.',
            'competence': '',
            'claimants': [''],
            'defendants': [''],
            'third_parties': [''],
            'claim_subject': '',
            'material': '',
            'case_price': '',
            'ground': '',
            'ground_square': '',
            'legality': '',
            'appealable': '',
            'complete': ''
    }
    ]
    return JsonResponse(result, safe=False)
